### PR TITLE
Added: install script

### LINKED ISSUE #451: Integration test for auto reload on config change
To make sure the auto reload feature don't break anymore in the future, we need to have an integration test for this.

### LINKED ISSUE #455: Add Auto Install Script in UNIX Installation
**Describe the issue**
In [Volta Getting Started](https://docs.volta.sh/guide/getting-started) page, it is said that it could be installed using CURL. We want to be able to create an installation flow like so, so that user without NPM installed can run Monika straight away.
image

**Expected behavior**
With a single CURL such as `https://monika.hyperjump.tech/get | bash`, we can install Monika.
The script should be:
1. Detect the operating system (Linux/MacOS)
2. Download the latest file from the release page according to their OS [https://github.com/hyperjumptech/monika/releases](https://github.com/hyperjumptech/monika/releases)
3. Extract the file, ask for sudo permissions to copy it to the /usr/local/bin
4. Update bash/zsh/fish startup file so that user can run `monika` later without having to modify the bashrc/zshrc/fishrc file
5. Confirm by running `monika -v`

**Additional context**
- Our website is https://monika.hyperjump.tech and we serve the page from the /docs folder using Github Pages. So if you want to add the endpoint for /get page, modify the contents of the /docs.

### PR DESCRIPTION
**Pull request by samsunoor**
# Monika Pull Request (PR)
This PR resolves #455 

## What feature/issue does this PR add  
1. Auto install script for linux and mac OS
2. Install script documentation

## How did you implement
1.  Added `scripts/monika-install.sh`
2. The script requires `curl` and `unzip`
3. The script will install monika into `$HOME/.monika` directory

## How to test
1. From project root directory run `./scripts/monika-install.sh`

### Screenshot
image

### CODE REVIEW

**Review by gsukanto — APPROVED** [review]

**Comment by sapiderman** [comment]
@samsunoor are not supporting windows? :innocent: :upside_down_face:  poor Windows(tm).

**Review by sapiderman — APPROVED** [review]
Tested on:
Description:	Pop!_OS 21.10
Release:	21.10
Running on : Alacritty terminal (bash)

image

**Comment by sapiderman** [comment]
@samsunoor works on WSL (ubuntu) on Win 11 .. yaay :plunger:
small issue with .bashrc path but otherwise works

**Comment by samsunoor** [comment]
Updated, removed auto-append `$PATH` from `.zshrc` and `.bashrc`

image

**Comment by nicnocquee** [comment]
Seems like no binary error?

Screenshot 2022-02-02 at 09 23 54

**Comment by samsunoor** [comment]
> Seems like no binary error?
@nicnocquee updated the script to require GNU grep for OSX (`ggrep`)

**Pull request merged**
