### PR TITLE
CI: Fix Broken Tests

### PR DESCRIPTION
**Pull request by haricnugraha**
# Monika Pull Request (PR)

## What feature/issue does this PR add
Fix broken tests when releasing Monika
- https://github.com/hyperjumptech/monika/actions/runs/6009497869/job/16299052049
- https://github.com/hyperjumptech/monika/actions/runs/6009497871/job/16299051850
- https://github.com/hyperjumptech/monika/actions/runs/6009497865/job/16299052069

## How did you implement / how did you fix it
Set environment variable `NODE_OPTIONS` to `'--no-experimental-fetch'` when running test

## How to test
Run `NODE_OPTIONS='--no-experimental-fetch' npm test`

### CODE REVIEW

**Review by raosan — APPROVED** [review]

**Review by raosan — COMMENTED** [review]
BTW, instead of using `NODE_OPTIONS`, how about changing the implementation of fetch to axios? because we also need to add the `NODE_OPTIONS` when running the `npm start`, otherwise it will show error for parts that using `fetch`

I implemented that in the mailgun PR:
- https://github.com/hyperjumptech/monika/pull/1105/commits/16d34183621a4f232c84704f2f9067d991a83c61
- https://github.com/hyperjumptech/monika/pull/1105/commits/9a32ec855c081d42f8f2d64d8f46747307860c0c

**Comment by haricnugraha** [comment]
> BTW, instead of using `NODE_OPTIONS`, how about changing the implementation of fetch to axios? because we also need to add the `NODE_OPTIONS` when running the `npm start`, otherwise it will show error for parts that using `fetch`
> 
> I implemented that in the mailgun PR:
> 
> * [16d3418](https://github.com/hyperjumptech/monika/commit/16d34183621a4f232c84704f2f9067d991a83c61)
> * [9a32ec8](https://github.com/hyperjumptech/monika/commit/9a32ec855c081d42f8f2d64d8f46747307860c0c)

This is a workaround for [this issue on MSW](https://github.com/mswjs/msw/issues/1388). I can't change the implementation inside the MSW library. 

It won't happen if you run `npm start` because MSW only used when running test.

**Comment by raosan** [comment]
> > BTW, instead of using `NODE_OPTIONS`, how about changing the implementation of fetch to axios? because we also need to add the `NODE_OPTIONS` when running the `npm start`, otherwise it will show error for parts that using `fetch`
> > I implemented that in the mailgun PR:
> > 
> > * [16d3418](https://github.com/hyperjumptech/monika/commit/16d34183621a4f232c84704f2f9067d991a83c61)
> > * [9a32ec8](https://github.com/hyperjumptech/monika/commit/9a32ec855c081d42f8f2d64d8f46747307860c0c)
> 
> This is a workaround for [this issue on MSW](https://github.com/mswjs/msw/issues/1388). I can't change the implementation inside the MSW library.
> 
> It won't happen if you run `npm start` because MSW only used when running test.

No, I mean change the implementation in the monika, not the `msw`. Since ther is only 3 places that use `fetch`

**Comment by haricnugraha** [comment]
> > > BTW, instead of using `NODE_OPTIONS`, how about changing the implementation of fetch to axios? because we also need to add the `NODE_OPTIONS` when running the `npm start`, otherwise it will show error for parts that using `fetch`
> > > I implemented that in the mailgun PR:
> > > 
> > > * [16d3418](https://github.com/hyperjumptech/monika/commit/16d34183621a4f232c84704f2f9067d991a83c61)
> > > * [9a32ec8](https://github.com/hyperjumptech/monika/commit/9a32ec855c081d42f8f2d64d8f46747307860c0c)
> > 
> > 
> > This is a workaround for [this issue on MSW](https://github.com/mswjs/msw/issues/1388). I can't change the implementation inside the MSW library.
> > It won't happen if you run `npm start` because MSW only used when running test.
> 
> No, I mean change the implementation in the monika, not the `msw`. Since ther is only 3 places that use `fetch`
> 
> And yes, I am not talking about the test, but when developing. It will show error when `npm start` using config that uses fetch such as pagerduty, mailgun.

Ok. I got your point.

1. This PR only fix the broken release pipeline
2. There is a problem with fetch when run the `npm start` command, you should create an issue for this
3. We're in the middle of replacing Axios with fetch, changing fetch with Axios is going backward

Could we agree on this?

**Comment by raosan** [comment]
> > > > BTW, instead of using `NODE_OPTIONS`, how about changing the implementation of fetch to axios? because we also need to add the `NODE_OPTIONS` when running the `npm start`, otherwise it will show error for parts that using `fetch`
> > > > I implemented that in the mailgun PR:
> > > > 
> > > > * [16d3418](https://github.com/hyperjumptech/monika/commit/16d34183621a4f232c84704f2f9067d991a83c61)
> > > > * [9a32ec8](https://github.com/hyperjumptech/monika/commit/9a32ec855c081d42f8f2d64d8f46747307860c0c)
> > > 
> > > 
> > > This is a workaround for [this issue on MSW](https://github.com/mswjs/msw/issues/1388). I can't change the implementation inside the MSW library.
> > > It won't happen if you run `npm start` because MSW only used when running test.
> > 
> > 
> > No, I mean change the implementation in the monika, not the `msw`. Since ther is only 3 places that use `fetch`
> > And yes, I am not talking about the test, but when developing. It will show error when `npm start` using config that uses fetch such as pagerduty, mailgun.
> 
> Ok. I got your point.
> 
> 1. This PR only fix the broken release pipeline
> 2. There is a problem with fetch when run the `npm start` command, you should create an issue for this
> 3. We're in the middle of replacing Axios with fetch, changing fetch with Axios is going backward
> 
> Could we agree on this?

I could agree for now, just looks a little dirty since it's a workaround and need to add `NODE_OPTION` for every `npm test` command

**Comment by haricnugraha** [comment]
> > > > > BTW, instead of using `NODE_OPTIONS`, how about changing the implementation of fetch to axios? because we also need to add the `NODE_OPTIONS` when running the `npm start`, otherwise it will show error for parts that using `fetch`
> > > > > I implemented that in the mailgun PR:
> > > > > 
> > > > > * [16d3418](https://github.com/hyperjumptech/monika/commit/16d34183621a4f232c84704f2f9067d991a83c61)
> > > > > * [9a32ec8](https://github.com/hyperjumptech/monika/commit/9a32ec855c081d42f8f2d64d8f46747307860c0c)
> > > > 
> > > > 
> > > > This is a workaround for [this issue on MSW](https://github.com/mswjs/msw/issues/1388). I can't change the implementation inside the MSW library.
> > > > It won't happen if you run `npm start` because MSW only used when running test.
> > > 
> > > 
> > > No, I mean change the implementation in the monika, not the `msw`. Since ther is only 3 places that use `fetch`
> > > And yes, I am not talking about the test, but when developing. It will show error when `npm start` using config that uses fetch such as pagerduty, mailgun.
> > 
> > 
> > Ok. I got your point.
> > 
> > 1. This PR only fix the broken release pipeline
> > 2. There is a problem with fetch when run the `npm start` command, you should create an issue for this
> > 3. We're in the middle of replacing Axios with fetch, changing fetch with Axios is going backward
> > 
> > Could we agree on this?
> 
> I could agree for now. It's just looks a little dirty since it's a workaround and need to add `NODE_OPTION` for every `npm test` command

Ok. So, I close this PR because it will be fixed by PR https://github.com/hyperjumptech/monika/pull/1105

**Pull request closed without merging**
