### PR TITLE
#991 refactor complex functions in validate.ts

### PR DESCRIPTION
**Pull request by ilmiawan**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  
containing two major functions that is very complex:
1. validateNotifications
2. validateConfig

## How did you implement / how did you fix it  
refactoring those 2 functions into multiple units and components 

## How to test  
1. run test for monika : "npm test" 
2. run codescene test

## screenshot
Screenshot 2023-02-15 at 14 33 59

### CODE REVIEW

**Comment by dennypradipta** [comment]
CMIIW, and I don't know if it's a good thing or not, should we move all the files that started with `validate-` into a folder called `validators`?

Like this?

└── validation/
    ├── index.ts
    ├── notification-required-fields.ts
    └── validators/
        ├── alert.ts
        ├── config-file.ts
        ├── mongo-config.ts
        └── ...

**Review by sapiderman — APPROVED** [review]
👁️ 👀 👓 
much clearer!

**Comment by ilmiawan** [comment]
> 

we can do this for a more clearer and modular code division

**Review by haricnugraha — APPROVED** [review]
LGTM!

**Pull request merged**
