### PR TITLE
adding option to allow probing invalid ssl endpoint

### PR DESCRIPTION
**Pull request by JesusIslam**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Adding option to allow probing invalid ssl endpoint

## How did you implement / how did you fix it  
1.  Adding configuration `allowUnauthorized` and used in creating http request, if detected this will make https agent with `rejectUnauthorized` set to false

## How to test  
1. Make probe request to `https://expired.badssl.com/` or other invalid ssl cert from badssl.com

### CODE REVIEW

**Comment by dennypradipta** [comment]
Hi @JesusIslam thank you for your PR!

Your PR looks great, it just needs a little touch: Could you add the `allowUnauthorized` flag in the documentation? To be precise, it is located in [https://monika.hyperjump.tech/guides/probes](https://monika.hyperjump.tech/guides/probes)

You can edit the documentation markdown at `docs/src/pages/guides/probes.md`

**Comment by JesusIslam** [comment]
> Hi @JesusIslam thank you for your PR!
> 
> Your PR looks great, it just needs a little touch: Could you add the `allowUnauthorized` flag in the documentation? To be precise, it is located in https://monika.hyperjump.tech/guides/probes
> 
> You can edit the documentation markdown at `docs/src/pages/guides/probes.md`

Hi @dennypradipta , I've made some changes you've requested. Let me know if it's not enough.

**Review by dennypradipta — APPROVED** [review]
LGTM

**Review by sapiderman — APPROVED** [review]
Good PR, good use case.
👍🏽  👏🏽 🤝

**Pull request merged**
