### PR TITLE
Fix/issue 599

### PR DESCRIPTION
**Pull request by nicnocquee**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Issue #599 

## How did you implement / how did you fix it  
1.  Update the pkg version. Seems like there is a glitch in the patched node base for macOS which was included in the previous pkg version. Hence, the error when running the stand alone monika binary.
2. Create the binary using node 14. Node 12 is nearing end of life, so let's use minimum 14. Not 16 yet because sqlite 3 doesn't seem to support node 16 yet at this moment.
3. Add the sqlite3 bindings in the `assets` key in package.json. With this, we don't need to manually copy node_sqlite3.node anymore. The latest pkg will automatically include it as an asset.

## How to test  
1. Use Node 14.19.1 (the latest 14): Run `nvm install 14` if you use nvm.
1. Run `npm run pkg`
2. Run `cd dist && ./monika`. Note, please run the generated monika with both a valid monika.yml and without any configuration where it should show error.

## Note

While this PR is supposed to fix the generation of macOS stand alone binary, it affects the windows and linux platform as well. So please run the commands in the How to Test section above in Linux and windows as well to make sure the binaries are generated correctly on the respective platform.

### CODE REVIEW

**Comment by raosan** [comment]
on Mac, failed on steo run `npm run pkg`
Screen Shot 2022-04-11 at 10 59 39

**Review by samsunoor — APPROVED** [review]
it works on linux
image

**Comment by sapiderman** [comment]
~/w/_/monika_main   fix/issue-599 …  npm run pkg 

> @hyperjumptech/monika@1.7.1 pkg /home/budhi/work/__TEST__/monika_main
> npm run prepack && pkg . --compress brotli

> @hyperjumptech/monika@1.7.1 prepack /home/budhi/work/__TEST__/monika_main
> npm run clean && tsc -b && oclif manifest

> @hyperjumptech/monika@1.7.1 clean /home/budhi/work/__TEST__/monika_main
> rm -rf coverage lib tsconfig.tsbuildinfo oclif.manifest.json

wrote manifest to /home/budhi/work/__TEST__/monika_main/oclif.manifest.json
> pkg@5.3.1
compression: Brotli
> Fetching base Node.js binaries to PKG_CACHE_PATH

fetched-v14.17.2-linux-x64 [====================] 100%
fetched-v14.17.2-macos-x64 [====================] 100%
fetched-v14.17.2-win-x64 [====================] 100%

> Warning Failed to make bytecode node14-x64 for file /snapshot/monika_main/node_modules/ky/index.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/monika_main/node_modules/ky/index.js
> Warning Failed to make bytecode node14-x64 for file C:\snapshot\monika_main\node_modules\ky\index.js

got some snapshot creation error, is this ok?

**Review by sapiderman — APPROVED** [review]
works on Linux release 21.10 for me! :trophy::trophy::trophy:

**Review by raosan — APPROVED** [review]
works on Windows too

**Pull request merged**
