### PR TITLE
Refactor: Make the Probe Result a Mandatory Type

### PR DESCRIPTION
**Pull request by haricnugraha**
# Monika Pull Request (PR)

## What feature/issue does this PR add
Currently, the probe result is an optional type and http and tls prober does not return the result. To make it predictable and prevents bug in the future, the probe result must be mandatory

## How did you implement / how did you fix it
Make the probe result a mandatory type and add the result to the http and tls prober

## How to test
1. Run Monika as usual
2. Run the test

### CODE REVIEW

**Review by raosan — APPROVED** [review]
LGTM

**Review by sapiderman — COMMENTED** [review]
can you please check that this config works? I have an issue with non-http probes working:

```yaml
probes:
  - id: 'psql-1'
    name: 'psql-test'
    postgres:
      - uri: 'postgresql://user:password@172.17.0.1:5432'
    alerts:
      - assertion: response.status < 200 or response.status > 299
        message: HTTP Status is not 200
      - assertion: response.time > 2000
        message: Response time is more than 2000ms
    incidentThreshold: 3
    recoveryThreshold: 3
    
    notifications:
  - id: desktop
    type: desktop
```

**Comment by haricnugraha** [comment]
> can you please check that this config works? I have an issue with non-http probes working:
> 
> ```yaml
> probes:
>   - id: 'psql-1'
>     name: 'psql-test'
>     postgres:
>       - uri: 'postgresql://user:password@172.17.0.1:5432'
>     alerts:
>       - assertion: response.status < 200 or response.status > 299
>         message: HTTP Status is not 200
>       - assertion: response.time > 2000
>         message: Response time is more than 2000ms
>     incidentThreshold: 3
>     recoveryThreshold: 3
>     
>     notifications:
>   - id: desktop
>     type: desktop
> ```

I think that is related to the issue on the PR https://github.com/hyperjumptech/monika/pull/1113. Will check once the PR 1113 got merged.

**Comment by sapiderman** [comment]
> > can you please check that this config works? I have an issue with non-http probes working:
> > ```yaml
> > probes:
> >   - id: 'psql-1'
> >     name: 'psql-test'
> >     postgres:
> >       - uri: 'postgresql://user:password@172.17.0.1:5432'
> >     alerts:
> >       - assertion: response.status < 200 or response.status > 299
> >         message: HTTP Status is not 200
> >       - assertion: response.time > 2000
> >         message: Response time is more than 2000ms
> >     incidentThreshold: 3
> >     recoveryThreshold: 3
> >     
> >     notifications:
> >   - id: desktop
> >     type: desktop
> > ```
> 
> I think that is related to the issue on the PR #1113. Will check once the PR 1113 got merged.

Will merge 1113 and try again. thank you

**Review by sapiderman — APPROVED** [review]
This works with #1113 merged. Nice job.

**Pull request merged**
