### PR TITLE
Refactor: Replace Manual Validation with Joi

### PR DESCRIPTION
**Pull request by haricnugraha**
# Monika Pull Request (PR)

## What feature/issue does this PR add
Replace manual validation with [Joi]( [Joi](https://joi.dev/)) validation for probe data input.

## How did you implement / how did you fix it
1. Change manual validation with Joi validation.
2. Remove the following unknown properties from Symon.

- locations
- notifications
- projectId
- recoveryThreshold
- requests[0].alerts[0].createdAt
- requests[0].alerts[0].updatedAt
- requests[0].createdAt
- requests[0].ipAddress
- requests[0].order
- requests[0].port
- requests[0].probeId
- requests[0].protocol
- requests[0].updatedAt

## How to test
1. Run Monika with invalid configuration.
4. Run Monika with valid configuration.
5. Run Monika in Symon mode.

#### Before
image

#### After
image

### Demo

Symon & Monika mode

https://github.com/hyperjumptech/monika/assets/15191978/e58145a2-0fbf-44d2-848e-fe98b1f4856a

### CODE REVIEW

**Comment by kevinhermawan** [comment]
Could you update `Joi` to the latest version too?

**Review by sapiderman — APPROVED** [review]
lots of good changes here, 👍🏽 🍺 🍻

**Review by dennypradipta — APPROVED** [review]
LGTM. What a legit PR as always @haricnugraha

**Review by raosan — APPROVED** [review]
LGTM

**Pull request merged**
