### PR TITLE
Added: Add Monika and OS Version in Notification Message

### LINKED ISSUE #424: Monika's version in all notification
To help us debug problems easier, let's also show the version of Monika in all notification messages.

For example, in the email

Message: Target is not healthy. The response time has been greater than 2000 ms.
URL: <url here>
Time: 2021-09-17 10:14:53 -04:00
From: hostname (ippublic/192.168.128.1). 
Version: @hyperjumptech/monika/1.6.0 linux-x64 node-v10.15.0

### PR DESCRIPTION
**Pull request by haricnugraha**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  
To help us debug problems easier, let's also show the version of Monika in all notification messages. Resolve #424.

## How did you implement / how did you fix it  
1. Get Monika and OS version and include it in the notification message.

## How to test  
1. Run `npm run test`.
3. Run Monika with notification configuration until it fails and send notification.
```yaml
notifications:
  - type: smtp
    data:
      recipients:
        - recipient1@example.com
      hostname: smtp.example.com
      port: 2525
      username: example
      password: secret
probes:
  - requests:
      - url: http://example.com
certificate:
  domains:
    - expired.badssl.com
```

### CODE REVIEW

**Review by gsukanto — APPROVED** [review]

**Review by nicnocquee — CHANGES_REQUESTED** [review]
The version doesn't show up in the starting notification.

Monika is running from Kilchberg - Swisscom (Schweiz) AG - Bluewin (IPADDRESS) - NMBPM1 (10.203.1.61)

**Review by sapiderman — COMMENTED** [review]
i'm not seeing it in the desktop notification/alert.

**Comment by haricnugraha** [comment]
> The version doesn't show up in the starting notification.
> 
> Monika is running from Kilchberg - Swisscom (Schweiz) AG - Bluewin (IPADDRESS) - NMBPM1 (10.203.1.61)

Updated here [2ef9eb2](https://github.com/hyperjumptech/monika/pull/429/commits/2ef9eb2223472eec8ab428bd2f27da3b06f83789).

**Comment by haricnugraha** [comment]
> i'm not seeing it in the desktop notification/alert.

Updated here [2ef9eb2](https://github.com/hyperjumptech/monika/pull/429/commits/2ef9eb2223472eec8ab428bd2f27da3b06f83789).

**Review by nicnocquee — APPROVED** [review]

**Pull request merged**
