### PR TITLE
New Notification: Gotify

### PR DESCRIPTION
**Pull request by nilsglow**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  

1. added new Notification type for Gotify (https://gotify.net)

## How did you implement / how did you fix it  

1.  Followed docs for new notification and adapted Pushover, which has similar mechnics

## How to test  

1. Install a Gotify server: https://gotify.net/docs/install
2. Create application token inside Gotify
3. Configure notification type according to guides/notifications#gotify
4. See notifications in Gotify web interface and configured clients

### CODE REVIEW

**Comment by dennypradipta** [comment]
Hi @nilsglow thank you for your PR!

Could you provide any screenshots about the notification sent to the Gotify?

**Comment by nilsglow** [comment]
Hi @dennypradipta, sorry for the slow response.

This is a screenshot of the web client:

Screenshot Gotify for PR

And this is how it looks in the Android app:

Screenshot Gotify Android for PR

I added the Monika logo when I configured the app channel in Gotify.

Let me know if I you need anything else in order to accept the PR!

**Review by dennypradipta — APPROVED** [review]
Thank you @nilsglow for your response. Looks good to me!

**Review by kevin-hyperjump — APPROVED** [review]
LGTM!

**Pull request merged**
