### PR TITLE
fix(http): handle axios error code UNABLE_TO_VERIFY_LEAF_SIGNATURE

### LINKED ISSUE #1266: Handle CERT_HAS_EXPIRED error
This just in, CERT_HAS_EXPIRED still not handled using Monika error handler

image

### PR DESCRIPTION
**Pull request by syamsudotdev**
# Monika Pull Request (PR)
This PR resolves #1266 

## What feature/issue does this PR add

1. Handle axios error code `UNABLE_TO_VERIFY_LEAF_SIGNATURE`

## How did you implement / how did you fix it

1. Map error code `UNABLE_TO_VERIFY_LEAF_SIGNATURE` to error code 27
2. Map error code `UNABLE_TO_VERIFY_LEAF_SIGNATURE` to error codename `ELEAFSIGNATURE`
3. Add documentation for error code 27

## How to test

1. Create `monika.yml` config below
```yaml
probes:
  - id: 'Example'
    requests:
      - url: https://kemendesa.go.id/
```
2. `npm run start -- -r 1`
3. On 5th failure, expect to see warning log `id:Example ERROR: EINVALIDLEAFSIGN: Unable to verify the first / leaf certificate., NOTIF: Service probably down`

### CODE REVIEW

**Comment by dennypradipta** [comment]
CMIIW, is the UNABLE_TO_VERIFY_LEAF_SIGNATURE the same as the CERT_HAS_EXPIRED?

If by chance it is different, maybe you could add CERT_HAS_EXPIRED as well.

**Comment by dennypradipta** [comment]
On second thought, the CERT_HAS_EXPIRED happens if you don't use `--ignoreInvalidTLS`, but UNABLE_TO_VERIFY_LEAF_SIGNATURE still happens. Carry on then

**Review by dennypradipta — APPROVED** [review]
LGTM

**Review by raosan — APPROVED** [review]
LGTM

**Pull request merged**
