### PR TITLE
Feat: Publish to Snapcraft

### PR DESCRIPTION
**Pull request by dennypradipta**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  
This PR solve #586 

## How did you implement / how did you fix it  
I added a Github Action to publish to Snapcraft. A `STORE_LOGIN` secret must be defined first.

## How to test  
N/A, but you can check it here as proof [https://github.com/dennypradipta/monika/runs/5140004811?check_suite_focus=true](https://github.com/dennypradipta/monika/runs/5140004811?check_suite_focus=true)
image

## Additional context
~~Still wondering how to change the version to the release version when pushing to Snapcraft instead of the git message~~ **DONE**

### CODE REVIEW

**Comment by dennypradipta** [comment]
Finally managed to get the tag version as the Snapcraft version:
image

Running with Monika (Snap edition)
image

**Review by gsukanto — APPROVED** [review]

**Review by sapiderman — APPROVED** [review]
It works! 

image

**Comment by sapiderman** [comment]
minor feedback: maybe update the email/account from personal denny-hyperjump to official hyperjump admin account?

**Comment by dennypradipta** [comment]
PR back to draft because of permission issues when running Monika using the uploaded Snap store version

**Comment by dennypradipta** [comment]
Found an answer on why ping doesn't work: It's because of the `network-observe`, not auto-connecting when installed. Currently proposing to auto-connect to Snapcraft [https://snapcraft.io/docs/reviewing-classic-confinement-snaps](https://snapcraft.io/docs/reviewing-classic-confinement-snaps)

**Review by sapiderman — APPROVED** [review]
👍🏽 👍🏽 👍🏽

**Comment by dennypradipta** [comment]
Tested in 3 machines:
image
image
image

All is well, I've updated the README and the Quick Start guide with the Snapcraft badge

**Pull request merged**
