### PR TITLE
Fix: Cluttered report data from monika to symon

### PR DESCRIPTION
**Pull request by ilmiawan**
# Monika Pull Request (PR)

## What feature/issue does this PR add
#1197 Cluttered Report data

## How did you implement / how did you fix it
1. Remove cluttered unused data to send probe report in symon-mode

## How to test
1. run symon
2. run monika in symon-mode
3. make sure the new report is entering to the symon report

Screenshot 2023-11-27 at 18 38 45

Screenshot 2023-11-27 at 18 38 04

### CODE REVIEW

**Comment by haricnugraha** [comment]
I could not see any file changes. Have you push it to the remote branch?

**Comment by ilmiawan** [comment]
> I don't see any file changes. Have you pushed it to the remote branch?

@haricnugraha this should be the changes https://github.com/hyperjumptech/monika/pull/1198/files on 1 file only. history.ts

**Comment by haricnugraha** [comment]
> > I don't see any file changes. Have you pushed it to the remote branch?
> 
> @haricnugraha this should be the changes https://github.com/hyperjumptech/monika/pull/1198/files on 1 file only. history.ts

Ok. It just appears on my end now, i don't know why.

**Review by haricnugraha — APPROVED** [review]

**Review by dennypradipta — APPROVED** [review]
Nicely done

**Review by raosan — APPROVED** [review]

**Review by sapiderman — APPROVED** [review]

**Pull request merged**
