### PR TITLE
Set monika to be able to run with minimum config

### PR DESCRIPTION
**Pull request by ilmiawan**
# Monika PR
## What issue this PR is trying to solve
The current config.json is a bit overwhelming, too many options.
Monika should be able to run with minimum request url configuration.

## How this PR solve the issue
Set the default alerts and name if not provided in configuration.

## How to test
set configuration into :
``{
  "probes": [
     {
      "request": {
        "url": "the-url"
      }
    }
  ]
}``

run monika.

### CODE REVIEW

**Review by gsukanto — APPROVED** [review]
lgtm

**Review by nicnocquee — CHANGES_REQUESTED** [review]
This PR causes these bug:

- Incident is not detected.

**Comment by nicnocquee** [comment]
Also, I thought we decided to use 2 seconds threshold for response-time-greater-than alert. But this PR uses 400 ms.

```
Warning: Probe probe_1 has no Alerts configuration defined. Using the default status-not-2xx and response-time-greater-than-400-ms
```

**Comment by ilmiawan** [comment]
> Also, I thought we decided to use 2 seconds threshold for response-time-greater-than alert. But this PR uses 400 ms.
> 
> ```
> Warning: Probe probe_1 has no Alerts configuration defined. Using the default status-not-2xx and response-time-greater-than-400-ms
> ```

Yes it should been for 2 s. I have fixed the alert status. Please check again.

**Comment by ilmiawan** [comment]
> This PR causes these bug:
> 
> * Incident is not detected.
> 
> Screenshot 2021-03-29 at 08 24 05

fixed and updated. Please check again.

**Review by dennypradipta — APPROVED** [review]

**Review by nicnocquee — APPROVED** [review]

**Pull request merged**
