### PR TITLE
Allow Multiple Request in One Probe for Request Chaining

### PR DESCRIPTION
**Pull request by dennypradipta**
# Monika PR

## What does this PR solve?

This PR solve first phase of issue #82 :

[x] The requests should be perform one after another.
[x] If a request fails (status-not-2xx or response-time-greater-than), the next requests should not be performed.
[x] Like before, the notifications are only sent when the alert has been triggered more than the incidentThreshold.

## How do you implement this?

I made changes to the `request` key in `probe` object, which is to change singular object into an array of objects and rename it to `requests`. Then, I configured the `components/http-probe` to probe URLs sequentially using `for await`

## How do I test this?

1. Use this configuration below:
```
{
  "notifications": [
    <YOUR_NOTIFICATION_SETTINGS_HERE>
  ],
  "probes": [
    {
      "id": "1",
      "name": "Example",
      "description": "Probe",
      "interval": 10,
      "requests": [
        {
          "method": "GET",
          "url": "https://github.com",
          "timeout": 7000
        },
        {
          "method": "GET",
          "url": "https://dennypradipta.com",
          "timeout": 7000
        },
        {
          "method": "GET",
          "url": "https://www.indorelawan.org",
          "timeout": 7000
        }
      ],
      "incidentThreshold": 3,
      "recoveryThreshold": 3,
      "alerts": ["status-not-2xx", "response-time-greater-than-300-ms"]
    }
  ]
}
```
2. Run MONIKA with configuration above

## Additional Context

Please bear in mind that this PR does not include the phase 2, which is to use the response body from previous requests. This only solve 3 points I mentioned at the "What does this PR solves?" section.

### Screenshots
image

### CODE REVIEW

**Review by nicnocquee — APPROVED** [review]

**Comment by armedi** [comment]
I got this one error in test

```sh
1) monika
       runs with normal config:
     RangeError: Invalid count value
      at String.repeat (<anonymous>)
      at Object.module.exports [as default] (node_modules/boxen/index.js:133:24)
      at Object.exports.validateConfig (src/utils/validate-config.ts:44:24)
      at Monika.run (src/index.ts:25:69)
      at Monika._run (node_modules/@oclif/command/lib/command.js:43:20)
      at Context.run (node_modules/fancy-test/lib/base.js:68:25)
```

**Review by kevinhermawan — APPROVED** [review]

**Review by armedi — APPROVED** [review]
1) monika
       runs with normal config:
     RangeError: Invalid count value
      at String.repeat (<anonymous>)
      at Object.module.exports [as default] (node_modules/boxen/index.js:133:24)
      at Object.exports.validateConfig (src/utils/validate-config.ts:44:24)
      at Monika.run (src/index.ts:25:69)
      at Monika._run (node_modules/@oclif/command/lib/command.js:43:20)
      at Context.run (node_modules/fancy-test/lib/base.js:68:25)

**Comment by haricnugraha** [comment]
> 1. monika
>    runs with normal config:
>    RangeError: Invalid count value
>    at String.repeat ()
>    at Object.module.exports [as default] (node_modules/boxen/index.js:133:24)
>    at Object.exports.validateConfig (src/utils/validate-config.ts:44:24)
>    at Monika.run (src/index.ts:25:69)
>    at Monika._run (node_modules/@oclif/command/lib/command.js:43:20)
>    at Context.run (node_modules/fancy-test/lib/base.js:68:25)

Please create issue for this.

**Comment by dennypradipta** [comment]
> > 1. monika
> >    runs with normal config:
> >    RangeError: Invalid count value
> >    at String.repeat ()
> >    at Object.module.exports [as default] (node_modules/boxen/index.js:133:24)
> >    at Object.exports.validateConfig (src/utils/validate-config.ts:44:24)
> >    at Monika.run (src/index.ts:25:69)
> >    at Monika._run (node_modules/@oclif/command/lib/command.js:43:20)
> >    at Context.run (node_modules/fancy-test/lib/base.js:68:25)
> 
> Please create issue for this.

Issue created at #109

**Pull request merged**
