### PR TITLE
Fix: Make Probe Requests Property Optional

### PR DESCRIPTION
**Pull request by haricnugraha**
# Monika Pull Request (PR)

## What feature/issue does this PR add
Make probe requests property optional

## How did you implement / how did you fix it
1. Add some tests
2. Make probe requests property optional
3. Add typeguard for the probe requests property

## How to test
1. Run local probe target. Run `cd dev && docker compose up`
2. Run Monika in verbose mode with the following configuration. Run `npm start -- --verbose`

```yaml
probes:
  - id: Hyperjump
    requests:
      - url: https://example.com
      - url: https://hyperjump.tech
  - id: mariadb
    interval: 2
    incidentThreshold: 1
    recoveryThreshold: 1
    mariadb:
      - host: localhost
        port: 3306
        username: mariadb_user
        password: mariadb_password
        database:
  - id: mysql
    interval: 2
    incidentThreshold: 1
    recoveryThreshold: 1
    mysql:
      - host: localhost
        port: 3307
        username: mysql_user
        password: mysql_password
        database:
  - id: mongo
    interval: 2
    incidentThreshold: 1
    recoveryThreshold: 1
    mongo:
      - uri: mongodb://mongo_user:mongo_password@localhost:27017
  - id: postgres
    interval: 2
    incidentThreshold: 1
    recoveryThreshold: 1
    postgres:
      - uri: postgres://postgres_user:postgres_password@localhost:5432/postgres_db
  - id: redis
    interval: 2
    incidentThreshold: 1
    recoveryThreshold: 1
    redis:
      - uri: redis://:redis_password@localhost:6379
```

## Video

https://github.com/hyperjumptech/monika/assets/15191978/57780444-516d-4a6a-af84-458f24cd69ad

### CODE REVIEW

**Review by sapiderman — APPROVED** [review]
Good PR 🏆 🍹 🐠

**Review by dennypradipta — COMMENTED** [review]
Nicely done, but might need to update the docs.

**Comment by haricnugraha** [comment]
> Nicely done, but might need to update the docs.

No need to update the documentation. Only the Typescript type has been changed to better reflect the configuration.

**Review by dennypradipta — APPROVED** [review]
LGTM but you might need to check the tests

**Comment by haricnugraha** [comment]
> LGTM but you might need to check the tests

Thank you for reviewing. I will work on making the test pass again.

**Pull request merged**
