### PR TITLE
Add script probe type

### PR DESCRIPTION
**Pull request by jgillick**
# Monika Pull Request (PR)  

## What feature/issue does this PR add  
* Feature: Adds a script probe type that will execute a local script for slightly more complex probes. The probe status will be the return value of the script (`0` == "success"). 
* Fix: The prometheus feature was breaking for non-request probes. (cannot destructure `request` in `collector.ts`)

## How did you implement / how did you fix it  
1.  Using the postgres probe as an example, I created a new script probe.
2. Wrote unit tests for the probe.
3. Added documentation.

## How to test  

**monika.yml**
```yml
probes:
  - id: '1'
    name: 'Script tests'
    script:
      - cmd: 'echo Hello World'
      - cmd: exit 123
      - cmd: sh probe.sh
```

**probe.sh**
```yml
#!/bin/sh
echo "Probing things..."
exit 0
```

### CODE REVIEW

**Comment by nicnocquee** [comment]
Hello @jgillick sorry for responding late for this PR, we're still discussing and trying this internally. I tried this PR but I have a question:

When a `probe` has multiple `cmd`s, say 3 commands, and the second command's exit is not `0`, any reasons why the third command is still executed? The behaviour of monika when a HTTP probe has multiple requests, the requests are chained, and if one fails, the subsequent requests won't be executed.

**Comment by jgillick** [comment]
Hi @nicnocquee. That's a great point. I can't see any reason they would continue to execute if one of them fails. I can update the PR sometime in the next week.

**Comment by jgillick** [comment]
@nicnocquee I've updated the PR to stop executing scripts in a probe when one fails.

**Review by sapiderman — APPROVED** [review]
It's a great idea, and looks ok. 
1. Will need a new PR for the jsonschema
2. The logs and notification maybe needs a rethink.

**Review by haricnugraha — APPROVED** [review]

**Comment by jgillick** [comment]
@sapiderman I have updated the PR for the JSON schema changes and synced upstream.

**Comment by nicnocquee** [comment]
Hey @jgillick apologies for the delayed response. We've been swamped with fixing implementations and integrating Monika with our SaaS. Unfortunately, we're closing this PR because we Monika is designed as a monitoring tool, and executing arbitrary scripts falls outside of its intended use. Thanks for your contribution, though. If the script execution feature is crucial for you, feel free to fork the project.

**Pull request closed without merging**
